### ISSUE TITLE
Small extra example

### ISSUE THREAD

**Issue by ImreC** [WilliamDASILVA/nuxt-stripe-module#1]
Hi,

Could you add a small example on how to retrieve the card after mounting it and convert it to a token? It's probably my lack of understanding, but I have tried a bunch of different ways and they all fail. 

Cheers!

**Comment by WilliamDASILVA** [comment]
@ImreC Hi there,

You may want to use the retrieveSource function from Stripe.js as documented here:
https://stripe.com/docs/stripe-js/reference#stripe-retrieve-source

In our specific case, to retrieve a source using the Id and the client secret id:
```js
{
  asyncData(context) {
    const { source, err } = await context.$stripe.import().retrieveSource({
      id: "src_18eYalAHEMiOZZp1l9ZTjSU0",
      client_secret: "src_client_secret_NibvRz4PMmJqjfb0sqmT7aq2",
    });
    // Do stuff
  },
}
```

For testing purposes, you can create a source like that:

```js
const { source } = await context.app.$stripe.import().createSource({
    type: 'card',
    token: 'tok_visa',
});

// You should use:
// source.id is the source id
// source.client_secret
```

Hope that helps you.

**Comment by o1lab** [comment]
Thanks for this nuxt module.

Im trying to use this.$stripe.import().createToken(card) in a vue method.

Following error is received: `error in creating token Error: Please use the same instance of `Stripe` you used to create this Element to create your Source or Token.`

Could you please add a working example in this repo - that will be really helpful.

Thank you.

**Comment by ameistad** [comment]
I'm also having the same issue. 

I got it working by doing this: 
```
let stripe
let elements
let card

export default {
  mounted () {
    stripe = this.$stripe.import()
    elements = stripe.elements()
    card = elements.create('card')
    card.mount(this.$refs.card)
  },  
  methods: {
    createPayment () {
      stripe.createToken(card)
      .then(result => {
        if (result.error) {
          console.log(result.error)
        } else {
          console.log(result.token)
          // handle stripe charge logic here.
        }
      })
    }
  },
}
```

**Comment by Denny143** [comment]
Hi
I have a question and pardon me if its too basic, I followed the discussions and tried using nuxt stripe module..I got the tokens created successfully as per @ameistad . But when I tried to create a charge, it gives an error on the console saying "Cannot read property 'create' of undefined".
here is what I tried out:
<script>
let stripe
let elements
let card
export default {
  mounted() {
    stripe = this.$stripe.import()
    elements = stripe.elements()
    card = elements.create("card")    
    card.mount(this.$refs.card)    
  },
 methods: {
    createPayment() {
      stripe.createToken(card).then(result => {
        if (result.error) {
          console.log(result.error)
        } else {
          //console.log(result.token)
          // handle stripe charge logic here.
          stripe.charges.create({
              amount: 999,
              currency: 'usd',
              description: 'Example charge',
              source: result.token,
            })
        }
      })
    },
  }
  
}
</script>
I am not sure how to make the 'create charges' working. Any help would be much appreciated. Thanks

**Comment by ImreC** [comment]
@Denny143 I found that this only happens on refresh and this is due to calling the create method before this.$stripe is available. Is solved it through putting the whole thing in a `setTimeout({},500)` block. Very hacky, but works. If anyone has a better suggestion I am all ears.

**Comment by ameistad** [comment]
I ended up ditching this module entirely because of issues like this. Got everything working by adding Stripe to the head in nuxt.config.js and using [vue-stripe-elements](https://github.com/fromatob/vue-stripe-elements).

nuxt.config.js
```
head {
  title: 'Nuxt Stripe example',
  script: [{ src: 'https://js.stripe.com/v3/' }],
  meta: ...
}

` ``

**Comment by Denny143** [comment]
Thanks @ameistad , I tried using vue stripe element as per your instruction and modified my code but I am getting same "Cannot read property 'create' of undefined" on my console here the code.


<template>
  <div id="app">
    <h1>Please give us your payment details:</h1>
    <card 
      :class="{ complete }"
      :options="stripeOptions"
      class="stripe-card"
      stripe="pk_test_0aFXYEzurxi5OUzYgGtBPqJs"
      @change="complete = $event.complete"
    />
    <v-btn :disabled="!complete" class="pay-with-stripe" @click="pay">Pay with credit card</v-btn>
  </div>
</template>
 
<script>
//import { stripeKey, stripeOptions } from "./stripeConfig.json"
import { Card, createToken, charges } from "vue-stripe-elements-plus"

export default {
  components: { Card },
  data() {
    return {
      complete: false,
      stripeOptions: {
        // see https://stripe.com/docs/stripe.js#element-options for details
      }
    }
  },
  methods: {
    pay() {
      // createToken returns a Promise which resolves in a result object with
      // either a token or an error key.
      // See https://stripe.com/docs/api#tokens for the token object.
      // See https://stripe.com/docs/api#errors for the error object.
      // More general https://stripe.com/docs/stripe.js#stripe-create-token.
      createToken().then(result => {
        if (result.error) {
          console.log(result.error)
        } else {
          //console.log(result.token)
          // handle stripe charge logic here.
          charges.create({
            amount: 999,
            currency: "usd",
            description: "Example charge",
            source: result.token
          })
        }
      })
    }
  }
}
</script> 
 
<style>
.stripe-card {
  width: 300px;
  border: 1px solid grey;
}
.stripe-card.complete {
  border-color: green;
}
</style>
Again any help would be much appreciated thanks

**Comment by connecteev** [comment]
@ameistad any chance you could share code for an end-to-end example using nuxt and code for charging on the backend? That would be really helpful.

**Comment by WilliamDASILVA** [comment]
Hey there,

This module now depends on the official [Stripe JS](https://www.npmjs.com/package/@stripe/stripe-js) integration. Please be aware of the **[BREAKING CHANGES in v3.0.0](https://github.com/WilliamDASILVA/nuxt-stripe-module/releases/tag/3.0.0)** and update your code accordingly.

If you have any concerns, please open a new issue!
