### ISSUE TITLE
Module not working on nuxt 2.2.0

### ISSUE THREAD

**Issue by maziarz** [WilliamDASILVA/nuxt-stripe-module#2]
Attempting to get it the module up and running. Followed the README, but ended up with following when trying to import stripe:

`app.js:507 TypeError: Cannot read property 'import' of undefined`

Component code:
```
  mounted: function () {
    const stripe = this.$stripe.import()
  }
``` 

What am i doing wrong?

**Comment by garrensweet** [comment]
@maziarz What were you doing wrong? I have the exact same issue and I'm certain the instructions have been followed to a T.

**Comment by kamran-ashlarglobal** [comment]
@garrensweet Have you found the solution for this?
