### ISSUE TITLE
How to make a secure connection

### ISSUE THREAD

**Issue by Sford4** [WilliamDASILVA/nuxt-stripe-module#21]
Hi all,

I've just added the component, hoping to capture customer info and create the necessary objects in stripe so i can charge payments from the backend.  Using the example code in the Usage section of the README, I end up with the credit card line but when I click into any of the fields I see the message `Automatic Credit card filling is disabled because this form does not use a secure connection`

I'm using the test publishableKey, how do I make this warning go away (ie, how do I make the form secure)?

**Comment by Sford4** [comment]
I'm also on localhost, does that warning only check for https?

**Comment by WilliamDASILVA** [comment]
Hello, yes it does only applies on https. This warning cannot be disabled through Stripe JS API.
