### ISSUE TITLE
stripeAccount option

### ISSUE THREAD

**Issue by uppergoal** [WilliamDASILVA/nuxt-stripe-module#24]
First, thanks for making this module possible. Would it be possible to add the option to provide a stripeAccount to support Stripe Connect. 
reference: https://stripe.com/docs/connect/creating-a-payments-page

Thanks

**Comment by WilliamDASILVA** [comment]
Hello, thank you for opening this issue.
I've published the v3.1.0 version including the `stripeAccount` option.
