### ISSUE TITLE
Stripe.js was loaded more than one time. Please only load it once per page.

### ISSUE THREAD

**Issue by filippolcr** [WilliamDASILVA/nuxt-stripe-module#3]
Using Nuxt 2.3 and  nuxt stripe module 2.0.0.
In nuxt.config:

```
modules: [
....
 ['nuxt-stripe-module', {
      version: 'v3',
      publishableKey: process.env.STRIPE_PUBLISHABLE_KEY
    }],
]
```
Chrome console warns me as follow:

> It looks like, Stripe.js was loaded more than one time. Please only load it once per page.

**Comment by aurelianoa** [comment]
> Using Nuxt 2.3 and nuxt stripe module 2.0.0.
> In nuxt.config:
> 
> ```
> modules: [
> ....
>  ['nuxt-stripe-module', {
>       version: 'v3',
>       publishableKey: process.env.STRIPE_PUBLISHABLE_KEY
>     }],
> ]
> ```
> 
> Chrome console warns me as follow:
> 
> > It looks like, Stripe.js was loaded more than one time. Please only load it once per page.

i solved by adding stripe to the data in my component and then loading this.stripe = this.$stripe.import() in the mounted() method, then using this.stripe on the rest of the component.

**Comment by WilliamDASILVA** [comment]
Hey there,

This module now depends on the official [Stripe JS](https://www.npmjs.com/package/@stripe/stripe-js) integration. Please be aware of the **[BREAKING CHANGES in v3.0.0](https://github.com/WilliamDASILVA/nuxt-stripe-module/releases/tag/3.0.0)** and update your code accordingly.

If you have any concerns, please open a new issue!
