### ISSUE TITLE
nuxt build failing in the latest release

### ISSUE THREAD

**Issue by askprateek** [WilliamDASILVA/nuxt-stripe-module#30]
![image](https://user-images.githubusercontent.com/9272830/111083038-7f443400-8531-11eb-8533-1170272a460a.png)

**Comment by leku451** [comment]
Failing for me as well

**Comment by WilliamDASILVA** [comment]
Oh sorry, I take a look at that tomorrow morning

**Comment by WilliamDASILVA** [comment]
It's fixed in the `3.1.6` release. Sorry for the trouble!
