### ISSUE TITLE
default value for `stripeAccount` header breaks ability to collect setupIntent from API

### ISSUE THREAD

**Issue by stuartpearman** [WilliamDASILVA/nuxt-stripe-module#31]
Noticed this was implemented recently, so it's a pretty fresh issue:
https://github.com/WilliamDASILVA/nuxt-stripe-module/issues/24

The `stripeAccount` header is for use with Stripe Connect only according to the Stripe docs:
https://stripe.com/docs/js/initializing#init_stripe_js-options-stripeAccount

Right now it default to an empty string. When I was testing it, the header was being sent and the stripe API was reading the empty string as a real client id, and returning this error:

```
message: "Only Stripe Connect platforms can work with other accounts. If you specified a client_id parameter, make sure it's correct. If you need to setup a Stripe Connect platform, you can do so at https://dashboard.stripe.com/account/applications/settings.",
type: "invalid_request_error"
```

When I tested removing the stripeAccount option, the request worked like normal

**Comment by WilliamDASILVA** [comment]
Hello, thank you for taking the time to report this.
I've made a quickfix **(3.1.7)** to avoid setting the `stripeAccount` at all if it was not specified in the options.

Sorry for the trouble!

**Comment by stuartpearman** [comment]
No problem, thank you sir!
