### ISSUE TITLE
this.$stripe is undefined.

### ISSUE THREAD

**Issue by scottcarlton** [WilliamDASILVA/nuxt-stripe-module#5]
Set up nuxtjs 2.8 and followed the instructions for adding the module but get `undefined` for `this.$stripe` anyone else have this issue or could suggest how to fix it?

**Comment by DmitriyKurto** [comment]
`nuxt 2.8.1` `this.$stripe` works fine
provide your code and nuxt.config settings

**Comment by scottcarlton** [comment]
I used the instructions found [ here ](https://github.com/WilliamDASILVA/nuxt-stripe-module#usage) and here is my `package.json` dependencies and my `nuxt.confiq` files modules. 
 
```
"dependencies": {
    "@nuxtjs/axios": "^5.3.6",
    "@nuxtjs/dotenv": "^1.3.0",
    "@nuxtjs/pwa": "^2.6.0",
    "cookie-universal-nuxt": "^2.0.16",
    "cross-env": "^5.2.0",
    "express": "^4.16.4",
    "firebase": "^6.2.4",
    "nuxt": "^2.8.1",
    "nuxt-stripe-module": "^2.0.0"
  },
```
```
modules: [
    '@nuxtjs/dotenv',
    'cookie-universal-nuxt',
    // Doc: https://axios.nuxtjs.org/usage
    '@nuxtjs/axios',
    '@nuxtjs/pwa',
    'nuxt-stripe-module'
  ],
  stripe: {
    version: 'v3',
    publishableKey: process.env.API_STRIPE_KEY,
  },
```
```
mounted() {
    console.log(this.$stripe) /// undefined
    const elements = this.$stripe.import().elements();
}
```

<img width="1202" alt="Screen Shot 2019-07-17 at 1 14 22 PM" src="https://user-images.githubusercontent.com/3724086/61404555-e90bc680-a894-11e9-853b-cb373fe2673d.png">

**Comment by DmitriyKurto** [comment]
@scottcarlton try to put your API_STRIPE_KEY directly in config:
`publishableKey: YOUR_KEY`
and check out

**Comment by suisun2015** [comment]
@DmitriyKurto 
I'm using nuxt 2.9.1 universal module.
I'm also finding ` this.$stripe /// undefined`
I wrote key at nuxt config.
Any way to resolve this error?

**Comment by WilliamDASILVA** [comment]
Hey there,

This module now depends on the official [Stripe JS](https://www.npmjs.com/package/@stripe/stripe-js) integration. Please be aware of the **[BREAKING CHANGES in v3.0.0](https://github.com/WilliamDASILVA/nuxt-stripe-module/releases/tag/3.0.0)** and update your code accordingly.

If you have any concerns, please open a new issue!
