### ISSUE TITLE
Just include on selected pages / URLs

### ISSUE THREAD

**Issue by bart** [WilliamDASILVA/nuxt-stripe-module#6]
Hi there,

is there any option to just include the Stripe SDK on selected pages? Just want to improve page speed and the SDK doesn't need to get loaded on pages where it isn't used.

Thanks and cheers!
bart

**Comment by l2aelba** [comment]
Yes please

**Comment by zacharytyhacz** [comment]
I agree, stripe is the main bottle neck within my application due to it's frequent requests on the page for the user. 

I also agree with @l2aelba by having this stripe added in the `<head>` because then with nuxt, we can only add stripe on the pages we need it to be on via the `head : {} ` options for a page. ( See [this](https://nuxtjs.org/api/pages-head) on the nuxt website)

**Comment by AKAI20020121** [comment]
Have any way to solve SDK loaded all pages.
I don't want to use `head` or `head: {}` options to set stripe.

**Comment by bjesus** [comment]
Anyone managed to workaround this?

**Comment by zacharytyhacz** [comment]
> Anyone managed to workaround this?

Have you tried importing stripe via cdn link in the `head : {}` of your page so it only loads on that page? It seems to be the only decent sort of work around

**Comment by bjesus** [comment]
That's what I ended up doing, yes. The problem was that I could never be sure when the Stripe script was loaded, and `window.Stripe` kept coming undefined. At the end I just spilt the form to two stages, and only when a user completes the first step I call `window.Stripe`, because by then I can be sure the script has loaded. It just feels like a ugly hack. and yeah, I got rid `nuxt-stripe-module` after doing this.

**Comment by connecteev** [comment]
@bjesus would you mind sharing your code in a repo? As an aside it would be really neat to have a nuxt repo for Stripe Payments https://stripe.com/docs/payments showing how it works end to end with a server like laravel cashier

**Comment by bjesus** [comment]
This is more or less how we're doing it on the Nuxt side, hope it helps:
```
<template lang="pug">
  div
    div(:class="{ 'd-none' : currentStep !== 1}")
      h2 Contact details
      .my-2
        b-form-input(type="email", placeholder="Your work e-mail", v-model="form.username", @focus="inputsState.email = null" :state="inputsState.email", name="username", required)
        b-form-invalid-feedback Please enter a valid work e-mail
      .my-2
        b-form-input(type="password", placeholder="Your new strong password", v-model="form.password", @focus="inputsState.password = null" :state="inputsState.password", name="password", required)
        b-form-invalid-feedback Please choose a longer password
      .text-center
        b-button(@click="moveToPayment" variant="primary" size="lg") Sign up
    div(:class="{ 'd-none' : currentStep !== 2}")
      h2 Payment details
      .mb-3.mt-4
        #card(style="border: 1px solid #ced4da; border-radius: 0.25rem;")
      .my-2
        b-form-checkbox(v-model='form.agree_to_terms', @click="inputsState.terms = null" :state="inputsState.terms" name="agree_to_terms")
          | I agree to the <a target="_blank" href="/signup/terms">terms of service</a>
      .text-center.mt-4
        b-button(@click="purchase" size="lg" variant="primary") Complete
</template>

<script>
export default {
  async asyncData({ env, params, $axios }) {
    return await $axios.$get("/payments/request/" + params.code);
  },
  data() {
    return {
      currentStep: 1,
      stripe: null,
      card: null,
      form: {
        username: "",
        password: "",
        agree_to_terms: false
      },
      inputsState: {
        email: null,
        password: null,
        terms: null
      }
    };
  },
  methods: {
    moveToPayment() {
      this.stripe = window.Stripe(process.env.STRIPE_KEY);
      const elements = this.stripe.elements();
      this.card = elements.create("card");
      this.card.mount("#card");
      const emailValid = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/.test(
        this.form.username
      );
      if (!emailValid) {
        this.inputsState.email = false;
      } else if (this.form.password.length < 7) {
        this.inputsState.password = false;
      } else {
        this.currentStep = 2;
      }
    },
    async purchase() {
      const _this = this;
      if (!this.form.agree_to_terms) {
        this.inputsState.terms = false;
        return;
      }
      let result = await _this.stripe.createToken(_this.card);
      if (result.token) {
        const response = await _this.$axios
          .$post("/payments/create", {
            token: result.token,
            email: this.form.username,
            password: this.form.password,
            request_id: this.$route.params.code
          })
          .catch(function(error) {
            _this.$sentry.captureException(error);
            console.log(error);
            alert(
              "We are sorry but something went wrong and we could not save your information. We were notified and we're working to fix it."
            );
          });
        if (response) {
          _this.currentStep = 3;
          _this.$auth.loginWith("local", {
            data: {
              strategy: "local",
              ..._this.form
            }
          });
        }
      } else {
        alert(
          "Sorry, but we could not process your card information. Please check the number you have entered."
        );
      }
    }
  },
  head() {
    return {
      title: "Payment",
      script: [{ src: "https://js.stripe.com/v3/" }]
    };
  }
};
</script>
```

**Comment by fabiofdsantos** [comment]
@bart 
Check this package: https://www.npmjs.com/package/nuxt-stripejs

**Comment by AlecWeekes** [comment]
Just wondering if this is something you intend to implement @WilliamDASILVA or whether the alternatives described in the comments are the best approach?

Loading Stripe on every page really isn't a viable solution. Even if I had to manually specify in the `nuxt.config.js` which pages I wanted this to load on, that'd be preferable. Any chance of this being possible?

**Comment by WilliamDASILVA** [comment]
@AlecWeekes Per the Stripe documentation, it's recommended to load Stripe on every page.
**See https://stripe.com/docs/js/including**

To understand what you guys are expecting, wouldn't it be easier for you just to rely on https://www.npmjs.com/package/@stripe/stripe-js and import it whenever you need it?

**Comment by bart** [comment]
Maybe it is recommended but WHY is it recommended? Makes no sense for me in terms of page speed optimization.

**Comment by fabiofdsantos** [comment]
I think that what makes no sense is forcing users to include stripe everywhere due to [fraud prevention](https://stripe.com/docs/disputes/prevention/advanced-fraud-detection), then allow to [disable the fraud prevention feature](https://stripe.com/docs/disputes/prevention/advanced-fraud-detection#disabling-advanced-fraud-detection) but still forcing to include the script in every single page.

However, if we import it whenever its needed.. there's no easy way to remove Stripe without reloading the application.

**Comment by SkullMasher** [comment]
> To understand what you guys are expecting, wouldn't it be easier for you just to rely on https://www.npmjs.com/package/@stripe/stripe-js and import it whenever you need it?

Sadly that's what I'm gonna do as it is also a huge [privacy concern](https://mtlynch.io/stripe-recording-its-customers/) for me on top of the performance problem.

@WilliamDASILVA I appreciate the work. Thank you for a flawless experience on my side with this module and the honesty of your answer.
